version: '2'

services:

  base:
    build:
      context: .
      dockerfile: Dockerfile.base
    image: 'cumuluss/geolambda:base'
    entrypoint: /bin/bash

  core:
    build:
      context: .
      dockerfile: Dockerfile.core
    image: 'cumuluss/geolambda:core'
    entrypoint: /bin/bash
    links:
      - base

  min:
    build:
      context: .
      dockerfile: Dockerfile.min
    image: 'cumuluss/geolambda:min'
    entrypoint: /bin/bash
    links:
      - core

  full:
    build:
      context: .
      dockerfile: Dockerfile.full
    image: 'cumuluss/geolambda:full'
    entrypoint: /bin/bash
    links:
      - core

  hdf:
    build:
      context: .
      dockerfile: Dockerfile.hdf
    image: 'cumuluss/geolambda:hdf'
    entrypoint: /bin/bash
    links:
      - core

  cloud:
    build:
      context: .
      dockerfile: Dockerfile.cloud
    image: 'cumuluss/geolambda:cloud'
    entrypoint: /bin/bash
    links:
      - core

#  runner:
#    build:
#      context: .
#      dockerfile: Dockerfile.runner
#    image: 'developmentseed/geolamnda:runner'
#    links:
#      - base
